# Defaults
defaults:
  - scope:
      path: "assets/images/clients"
    values:
      image: true

# Site settings
title: Boris Fründt – Technical Consulting & Development
email: boris.fruendt@gmail.com
description: >
  I'm Boris – Freelance technical consultant & developer from Hamburg. Nice to finally meet you! Let's meet.
favicon: "/favicon.ico"
logo: "/assets/images/share.jpg"
logo_alt: "Me wearing shirt and tie behind my logo and the domain name boris.io"
baseurl: ""
url: "https://boris.io"
name: 'Boris Fründt'
author_image: "/assets/images/logo.jpg"
publisher_image: "/assets/images/publisher.png"
twitter_username: bondt
github_username:  b0ndt

# Google Analytics
analytics_id: "UA-127964474-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-tidy
  - jekyll-assets

jekyll_tidy:
  compress_html: false

assets:
  source_maps: true
  destination: "/assets"
  compression: false
  gzip: false
  defaults:
    js: { integrity: false }
    css: { integrity: false }
    img: { integrity: false }
  caching:
    path: ".jekyll-cache/assets"
    type: file
    enabled: true
  precompile: []
  raw_precompile: [
    #
  ]
  cdn:
    baseurl: false
    destination: false
    url: null
  sources:
    - assets/css
    - assets/fonts
    - assets/images
    - assets/images/clients
    - assets/videos
    - assets/javascript
    - assets/video
    - assets/image
    - assets/img
    - assets/js
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/videos
    - _assets/javascript
    - _assets/video
    - _assets/image
    - _assets/img
    - _assets/js
    - css
    - fonts
    - images
    - videos
    - javascript
    - video
    - image
    - img
    - js
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}