# Defaults
defaults:
  - scope:
      path: "assets/images/clients"
    values:
      image: true

# Site settings
title: Boris Fründt
email: boris.fruendt@gmail.com
description: >
  Hey there! I'm Boris. Nice to finally meet you! If you would like to work with me, let's meet, let's discuss, let's collaborate and make innovative business together.
favicon: "/favicon.ico"
logo: "/assets/images/share.jpg"
baseurl: ""
url: "https://boris.io"
name: 'Boris Fründt'
author_image: "/assets/images/logo.jpg"
twitter_username: bondt
github_username:  b0ndt

# Google Analytics
analytics_id: "UA-127964474-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-tidy
  - jekyll-assets

jekyll_tidy:
  compress_html: false

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: false # true on JEKYLL_ENV=production
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  # --
  # Assets you wish to always have compiled.
  #   This can also be combined with raw_precompile which
  #   copies assets without running through the pipeline
  #   making them ultra fast.
  # --
  precompile: []
  raw_precompile: [
    #
  ]
  # --
  # baseurl: whether or not to append site.baseurl
  # destination: the folder you store them in on the CDN.
  # url: the CDN url (fqdn, or w/ identifier).
  # --
  cdn:
    baseurl: false
    destination: false
    url: null
  # --
  # These are all default. No need to add them
  #   Only use this if you have more.
  # --
  sources:
    - assets/css
    - assets/fonts
    - assets/images
    - assets/images/clients
    - assets/videos
    - assets/javascript
    - assets/video
    - assets/image
    - assets/img
    - assets/js
    - _assets/css
    - _assets/fonts
    - _assets/images
    - _assets/videos
    - _assets/javascript
    - _assets/video
    - _assets/image
    - _assets/img
    - _assets/js
    - css
    - fonts
    - images
    - videos
    - javascript
    - video
    - image
    - img
    - js
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}